---
- name: Ansible PPA key
  apt_key:
      keyserver: keyserver.ubuntu.com
      id: 93C4A3FD7BB9C367

- name: Ansible PPA repo
  apt_repository:
      repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu bionic main
      state: present

- name: Update Ansible package
  apt:
      name: ansible
      update_cache: yes
      state: latest

